# elasticSearch连接配置
elasticsearch-config:
  host: localhost
  port: 9200

# 日志配置
logging.level.*: DEBUG

logging:
  config: classpath:logback-boot.xml

# postgreSQL, redis连接配置
spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/sparrow
    password: ifihadyou
    driver-class-name: org.postgresql.Driver

    tomcat:
      max-active: 50
      max-idle: 10
      max-wait: 10000
      initial-size: 5
  redis:
    port: 6379
    host: localhost
    timeout: 1000ms
    jedis:
      pool:
        min-idle: 5
        max-active: 10
        max-idle: 10
        max-wait: 2000ms

# mybatis配置
mybatis:
  mapper-locations: classpath:com/micerlab/sparrow/mapper/*.xml
  type-aliases-package: com.micerlab.sparrow.domain.pojo
