


logging:
  config: classpath:logback-spring.xml

# postgreSQL, redis, rabbitmq连接配置
spring:
  profiles:
    active: dev
  datasource:
    username: postgres
    password: sparrowbackend
    driver-class-name: org.postgresql.Driver
    tomcat:
      max-active: 50
      max-idle: 10
      max-wait: 10000
      initial-size: 5
  redis:
    port: 6379
    host: ${sparrow.host}
    timeout: 1000ms
    jedis:
      pool:
        min-idle: 5
        max-active: 10
        max-idle: 10
        max-wait: 2000ms
  rabbitmq:
    host: ${sparrow.host}
    port: 5672
    username: guest
    password: guest

# mybatis配置
mybatis:
  mapper-locations: classpath:com/micerlab/sparrow/mapper/*.xml
  type-aliases-package: com.micerlab.sparrow.domain.pojo

minio:
  endpoint: 39.108.210.48:9000
  accessKey: SWLNR4NMXK02HG0K6BM6
  secretKey: 1sPE5q7oNEHpWPBZWdOgttFZyOg+YroItnq9P7wn
  bucketName: douban-test

oss:
  endpoint: http://oss-cn-beijing.aliyuncs.com
  accessKeyId: LTAInhMpeCqDsM4c
  accessKeySecret: RXxpqMZIlo7bwTIbX3MiAGgxdKX4v7
  bucketName: douban-test
  callbackHost: ${server.port}

# 使用39服务器的elasticSearch
elasticsearch-config:
  host: ${sparrow.host}
  port: 9200

server:
  port: 8089

---

# 开发环境，使用OpenVpn连接到39服务器
spring:
  profiles: dev
  datasource:
    url: jdbc:postgresql://${sparrow.host}:5432/sparrow

# 39.108.210.48服务器在OpenVpn虚拟局域网内的ip
sparrow:
  host: 10.0.0.1
  require-login: true

# ES索引命名
elasticsearch-config:
  indices:
    doc: spa_docs
    file: spa_files
    tag: spa_tags
    category: spa_categories
    group: spa_group
    user: spa_user

file:
  temp:
    path: D:\\sparrow\\temp\\



---

spring:
  profiles: prod
  datasource:
    url: jdbc:postgresql://localhost:5432/sparrow

# 生产环境，使用localhost
sparrow:
  host: localhost
  require-login: true

# ES索引命名
elasticsearch-config:
  indices:
    doc: spa_docs
    file: spa_files
    tag: spa_tags
    category: spa_categories
    user_group: spa_group
#    user: spa_user
#    group: spa_group
#    doc: docs
#    file: files
#    tag: tags
#    category: categories
#    user_group: groups

file:
  temp:
    path: /root/sparrow/temp

---
