

# 日志配置
logging.level.*: DEBUG

logging:
  config: classpath:logback-boot.xml

# postgreSQL, redis连接配置
spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://39.108.210.48:5432/sparrow
    password: sparrowbackend
    driver-class-name: org.postgresql.Driver
    tomcat:
      max-active: 50
      max-idle: 10
      max-wait: 10000
      initial-size: 5
  redis:
    port: 6379
    host: localhost
    timeout: 1000ms
    jedis:
      pool:
        min-idle: 5
        max-active: 10
        max-idle: 10
        max-wait: 2000ms
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

# mybatis配置
mybatis:
  mapper-locations: classpath:com/micerlab/sparrow/mapper/*.xml
  type-aliases-package: com.micerlab.sparrow.domain.pojo

minio:
  endpoint: 39.108.210.48:9000
  accessKey: SWLNR4NMXK02HG0K6BM6
  secretKey: 1sPE5q7oNEHpWPBZWdOgttFZyOg+YroItnq9P7wn
  bucketName: douban-test

oss:
  endpoint: http://oss-cn-beijing.aliyuncs.com
  accessKeyId: LTAInhMpeCqDsM4c
  accessKeySecret: RXxpqMZIlo7bwTIbX3MiAGgxdKX4v7
  bucketName: douban-test
  callbackHost: ${server.port}


server:
  port: 8089

